name: release

on:
  workflow_run:
    workflows: [ "test" ]
    types: [ completed ]

permissions:
  contents: write   # needed to create a release

jobs:
  make-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download verified artifact from Test run
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: myapp-verified-linux-amd64
          path: dist

      - name: Show file
        run: ls -lh dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "myapp v${{ github.run_number }}"
          body: |
            Automated release from CI chain
            - Built on ubuntu-latest
            - Verified via Test workflow
          files: |
            dist/myapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
