name: Test

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: myapp
      - run: ./myapp --version  # Example test
